name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test

      - name: Publish HTML Report
        uses: actions/upload-artifact@v4
        if: always() #failure() # caso queira só quando tiver erros
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7